server:
  port: 8010

spring:
  datasource:
    url: jdbc:mysql://122.51.112.207:3306/renhaomengmama?useUnicode=true&characterEncoding=utf8
    password: root
    username: Xiao@123
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  # 映射文件所在路径
  mapper-locations: classpath:mappers/*.xml